### PR TITLE
Feature/low speed correction

### PR DESCRIPTION
**Pull request by rbonghi**
This feature will solve #37 #36, time table operation:

- [X] Add normalization value of measured velocity and referecene @Myzhar 504058334dae51f450b8550e0c9727e758bc3c03 
- [X] Copy from @guiott code feature to IC prescaler @Myzhar f3966ebadbdba85ede4c8627fa2674fa695e76fc
- [x] Collect similar function in `motors_PID.c` in according with #27 @rbonghi 103c5dd798a9f10025c6a386307c3e728ea1b140
- [ ] Add measure velocity with QEI information (First release @Myzhar) 9eaaae9c58a58c2a1b355b0c8707bf3cc7081974
- [x] Move velocity measures in different interrupt at high frequency (Non in PID function)
- [ ] Add buffer array to measure velocity
- [x] Solve problem in prescaler switch

### CODE REVIEW

**Comment by rbonghi** [comment]
Task operation to evaluation position and velocity:

Operations on interrupt
1. acquire QEI register value - **fixed time based**
2. acquire timeperiod value from IC - **fixed space based**
3. add *1* in circular buffer - **fixed time based**
4. add *2* in circular buffer - **fixed space based**

Operations before evaluation velocity:
1. mean value from circular buffer  - **fixed time based**
2. velocity from **fixed time based** buffer
3. mean value from circular buffer  - **fixed space based**
4. velocity from **fixed space based** buffer
5. mean value between **fixed time based** and **fixed space based**

Operation before evaluation position:
1. sum all value from circular buffer - **fixed time based**
2. time period from last request of data position

@Myzhar Do you have other things?

**Comment by Myzhar** [comment]
@rbonghi that's good!

**Comment by rbonghi** [comment]
```diff
+    timePeriodL = overTmrL * PR2 + t2 - t1; // PR2 is 0xFFFF
+    overTmrL = 0;
-    if (overTmrL == 0) // TMR2 overflowed?
-    {// see Microchip AN545
-        timePeriodL += (t2 - t1);
-    }
-    else
-    {// [7a]
-        timePeriodL += (t2 + (PR2 - t1)
-          +(PR2 * (overTmrL - 1)));
-
-        overTmrL = 0;
-    }
```

It is the same code, because:

1. timePeriodL += (t2 + (PR2 - t1) +(PR2 * (overTmrL - 1)));
2. timePeriodL += t2 + PR2 - t1 + PR2 * overTmrL - PR2;
3. timePeriodL += t2 - t1 + PR2 * overTmrL;
4. timePeriodL += PR2 * overTmrL + t2 - t1;

Finally if `overTmrL` equal to zero:
timePeriodL += t2 - t1;

I don't understand why all timePeriod is summed with last value.
This part of code was a copy from https://code.google.com/p/dspid4w/source/browse/trunk/dsPID4W.X/src/dsPID4W.c#1357
(Copied by @Myzhar )

Question:
In this part of code we have to evaluate a mean value for sign (I remember this question in https://code.google.com/p/dspid4w/source/browse/trunk/dsPID4W.X/src/dsPID4W.c#1337 @guiott )
```c
(QEI1CONbits.UPDN ? SIG_VELL++ : SIG_VELL--); //Save sign Vel L
```
It is same a:
SIG_VEL = K * QEIXCONbits.UPDN;
where **K** is number of starts for `_ICXInterrupt` function, but when we evaluate the velocity in https://github.com/officinerobotiche/uNAV.X/blob/develop/src/control/motors_PID.c#L350
```c
motor.measure_vel = SIG_VEL * (parameter_motor.k_vel / timePeriod);
```
we obtain:
```c
motor.measure_vel = K * QEIXCONbits.UPDN * (parameter_motor.k_vel / timePeriod);
```
but we have **K** times the correct measure of velocity!

I think to a correct evaluation of velocity we must use:
```c
#define SGN(x)  ( ((x) < 0) ?  -1 : ( ((x) == 0 ) ? 0 : 1) )
motor.measure_vel = SGN(SIG_VEL) * (parameter_motor.k_vel / timePeriod);
```

cc @guiott

**Comment by rbonghi** [comment]
Sorry for my second post.

Question n°2 (principally for @guiott ):
Why do you use an incremental sum for `timePeriodX`?
In https://code.google.com/p/dspid4w/source/browse/trunk/dsPID4W.X/src/dsPID4W.c#1326
```c
Ic1Period += (Ic1CurrPeriod - Ic1PrevPeriod);
```
I think is correct to use only a difference between last sample, in according with my my code:
```c
timePeriodL = PR2 * overTmrL + t2 - t1;
```
in https://github.com/officinerobotiche/uNAV.X/blob/feature/low_speed_correction/src/system/interrupts.c#L156

**Comment by guiott** [comment]
I don’t exactly remember after so long time but, reading back to the code, it should be because of a possible, multiple reading before calculating speed and the related reset of the value: Ic1Period = 0;


> Il giorno 19/apr/2015, alle ore 13:19, Raffaello Bonghi <notifications@github.com <mailto:notifications@github.com>> ha scritto:
> 
> +    timePeriodL = overTmrL * PR2 + t2 - t1; // PR2 is 0xFFFF
> +    overTmrL = 0;
> -    if (overTmrL == 0) // TMR2 overflowed?
> -    {// see Microchip AN545
> -        timePeriodL += (t2 - t1);
> -    }
> -    else
> -    {// [7a]
> -        timePeriodL += (t2 + (PR2 - t1)
> -          +(PR2 * (overTmrL - 1)));
> -
> -        overTmrL = 0;
> -    }
> It is the same code, because:
> 
> timePeriodL += (t2 + (PR2 - t1) +(PR2 * (overTmrL - 1)));
> timePeriodL += t2 + PR2 - t1 + PR2 * overTmrL - PR2;
> timePeriodL += t2 - t1 + PR2 * overTmrL;
> timePeriodL += PR2 * overTmrL + t2 - t1;
> Finally if overTmrL equal to zero:
> timePeriodL += t2 - t1;
> 
> I don't understand why all timePeriod is summed with last value.
> This part of code was a copy from https://code.google.com/p/dspid4w/source/browse/trunk/dsPID4W.X/src/dsPID4W.c#1357 <https://code.google.com/p/dspid4w/source/browse/trunk/dsPID4W.X/src/dsPID4W.c#1357>
> (Copied by @Myzhar <https://github.com/Myzhar> )
> 
> Question:
> In this part of code we have to evaluate a mean value for sign (I remember this question in https://code.google.com/p/dspid4w/source/browse/trunk/dsPID4W.X/src/dsPID4W.c#1337 <https://code.google.com/p/dspid4w/source/browse/trunk/dsPID4W.X/src/dsPID4W.c#1337> @guiott <https://github.com/guiott> )
> 
> (QEI1CONbits.UPDN ? SIG_VELL++ : SIG_VELL--); //Save sign Vel L
> It is same a:
> SIG_VEL = K * QEIXCONbits.UPDN;
> where K is number of starts for _ICXInterrupt function, but when we evaluate the velocity in https://github.com/officinerobotiche/uNAV.X/blob/develop/src/control/motors_PID.c#L350 <https://github.com/officinerobotiche/uNAV.X/blob/develop/src/control/motors_PID.c#L350>
> motor.measure_vel = SIG_VEL * (parameter_motor.k_vel / timePeriod);
> we obtain:
> 
> motor.measure_vel = K * QEIXCONbits.UPDN * (parameter_motor.k_vel / timePeriod);
> but we have K times the correct measure of velocity!
> 
> I think to a correct evaluation of velocity we must use:
> 
> #define SGN(x)  ( ((x) < 0) ?  -1 : ( ((x) == 0 ) ? 0 : 1) )
> motor.measure_vel = SGN(SIG_VEL) * (parameter_motor.k_vel / timePeriod);
> cc @guiott <https://github.com/guiott>
> —
> Reply to this email directly or view it on GitHub <https://github.com/officinerobotiche/uNAV.X/pull/39#issuecomment-94266226>.
> 

___________________
http://www.guiott.com/ <http://www.guiott.com/>

**Comment by guiott** [comment]
> Il giorno 19/apr/2015, alle ore 13:19, Raffaello Bonghi <notifications@github.com> ha scritto:
> 
> +    timePeriodL = overTmrL * PR2 + t2 - t1; // PR2 is 0xFFFF
> +    overTmrL = 0;
> -    if (overTmrL == 0) // TMR2 overflowed?
> -    {// see Microchip AN545
> -        timePeriodL += (t2 - t1);
> -    }
> -    else
> -    {// [7a]
> -        timePeriodL += (t2 + (PR2 - t1)
> -          +(PR2 * (overTmrL - 1)));
> -
> -        overTmrL = 0;
> -    }
> It is the same code, because:
> 
> timePeriodL += (t2 + (PR2 - t1) +(PR2 * (overTmrL - 1)));
> timePeriodL += t2 + PR2 - t1 + PR2 * overTmrL - PR2;
> timePeriodL += t2 - t1 + PR2 * overTmrL;
> timePeriodL += PR2 * overTmrL + t2 - t1;
> Finally if overTmrL equal to zero:
> timePeriodL += t2 - t1;
> 
> 

Correct. Simpler, faster and more clear.

> I don't understand why all timePeriod is summed with last value.
> This part of code was a copy from https://code.google.com/p/dspid4w/source/browse/trunk/dsPID4W.X/src/dsPID4W.c#1357 <https://code.google.com/p/dspid4w/source/browse/trunk/dsPID4W.X/src/dsPID4W.c#1357>
> (Copied by @Myzhar <https://github.com/Myzhar> )
> 

Because the sampling of the speed with IC and its usage are always computed with different periods.
You are capturing the IC periods with the time imposed by the encoder, measuring the time between two pulses.

look here:
https://code.google.com/p/dspid4w/source/browse/trunk/dsPID4W.X/src/dsPID4W.c#1220 <https://code.google.com/p/dspid4w/source/browse/trunk/dsPID4W.X/src/dsPID4W.c#1220>

You compute the (mean) speed at the PID rate, e.g.: every 1ms
In this way you are measuring the total time for N pulses  occurred in 1ms (very close to 1ms but not exactly that because of discretization) = T
Then you measure the total space traveled = number of pulses * space-for-each-pulse = S
Then you divide the traveled space by the total period (about 1ms) = S/T = V

Simplifying and accepting a bit of approximation, you could even use T always = 1ms (or whatever PID sampling time), without measuring at all IC period, just counting the number of pulses occurred in between. At the contrary, if you want to be more precise, you can correct the measure calculating the difference between 1ms and the measured period.

Making a summation with the sign for the number of pulses:

https://code.google.com/p/dspid4w/source/browse/trunk/dsPID4W.X/src/dsPID4W.c#1370 <https://code.google.com/p/dspid4w/source/browse/trunk/dsPID4W.X/src/dsPID4W.c#1370>

takes care of the real traveled space, even if  the direction changes in between.

I hope tho have been clear enough:
1 - Get the period for one pulse 
2 - Sum the total time for N pulses occurred in one PID period
3 - Count, algebraically, the number of pulses N in one PID period
4 - Compute the space S traveled in one PID period multiplying N by space-for-each-pulse
5 - Compute the mean speed in one PID period = S/T

Of course this works if the period for one pulse is less then the PID period (at least one pulse in 1ms) and  the error is greater at low speed (less samples and therefore more quantization error).
Changing the mode (rising, falling, rising and falling) allows a better dynamics at high speed. In order to work also at very-very low speed, the PID period should be increased in that cases, being careful to the K parameters that can change.


> Question:
> In this part of code we have to evaluate a mean value for sign (I remember this question in https://code.google.com/p/dspid4w/source/browse/trunk/dsPID4W.X/src/dsPID4W.c#1337 <https://code.google.com/p/dspid4w/source/browse/trunk/dsPID4W.X/src/dsPID4W.c#1337> @guiott <https://github.com/guiott> )
> 
> (QEI1CONbits.UPDN ? SIG_VELL++ : SIG_VELL--); //Save sign Vel L
> It is same a:
> SIG_VEL = K * QEIXCONbits.UPDN;
> where K is number of starts for _ICXInterrupt function, but when we evaluate the velocity in https://github.com/officinerobotiche/uNAV.X/blob/develop/src/control/motors_PID.c#L350 <https://github.com/officinerobotiche/uNAV.X/blob/develop/src/control/motors_PID.c#L350>
> motor.measure_vel = SIG_VEL * (parameter_motor.k_vel / timePeriod);
> we obtain:
> 
> motor.measure_vel = K * QEIXCONbits.UPDN * (parameter_motor.k_vel / timePeriod);
> but we have K times the correct measure of velocity!
> 
> I think to a correct evaluation of velocity we must use:
> 
> #define SGN(x)  ( ((x) < 0) ?  -1 : ( ((x) == 0 ) ? 0 : 1) )
> motor.measure_vel = SGN(SIG_VEL) * (parameter_motor.k_vel / timePeriod);
> cc @guiott <https://github.com/guiott>
> —
> Reply to this email directly or view it on GitHub <https://github.com/officinerobotiche/uNAV.X/pull/39#issuecomment-94266226>.
> 

___________________
http://www.guiott.com/

**Comment by guiott** [comment]
Some more explanation is available here too:

https://code.google.com/p/dspid4w/source/browse/trunk/dsPID4W.X/src/descrEng.txt#570 <https://code.google.com/p/dspid4w/source/browse/trunk/dsPID4W.X/src/descrEng.txt#570>

on point [19] and subsequents 


> Il giorno 21/apr/2015, alle ore 00:19, Guido Ottaviani <guido@guiott.com> ha scritto:
> 
> 
>> Il giorno 19/apr/2015, alle ore 13:19, Raffaello Bonghi <notifications@github.com <mailto:notifications@github.com>> ha scritto:
>> 
>> +    timePeriodL = overTmrL * PR2 + t2 - t1; // PR2 is 0xFFFF
>> +    overTmrL = 0;
>> -    if (overTmrL == 0) // TMR2 overflowed?
>> -    {// see Microchip AN545
>> -        timePeriodL += (t2 - t1);
>> -    }
>> -    else
>> -    {// [7a]
>> -        timePeriodL += (t2 + (PR2 - t1)
>> -          +(PR2 * (overTmrL - 1)));
>> -
>> -        overTmrL = 0;
>> -    }
>> It is the same code, because:
>> 
>> timePeriodL += (t2 + (PR2 - t1) +(PR2 * (overTmrL - 1)));
>> timePeriodL += t2 + PR2 - t1 + PR2 * overTmrL - PR2;
>> timePeriodL += t2 - t1 + PR2 * overTmrL;
>> timePeriodL += PR2 * overTmrL + t2 - t1;
>> Finally if overTmrL equal to zero:
>> timePeriodL += t2 - t1;
>> 
>> 
> 
> Correct. Simpler, faster and more clear.
> 
>> I don't understand why all timePeriod is summed with last value.
>> This part of code was a copy from https://code.google.com/p/dspid4w/source/browse/trunk/dsPID4W.X/src/dsPID4W.c#1357 <https://code.google.com/p/dspid4w/source/browse/trunk/dsPID4W.X/src/dsPID4W.c#1357>
>> (Copied by @Myzhar <https://github.com/Myzhar> )
>> 
> 
> Because the sampling of the speed with IC and its usage are always computed with different periods.
> You are capturing the IC periods with the time imposed by the encoder, measuring the time between two pulses.
> 
> look here:
> https://code.google.com/p/dspid4w/source/browse/trunk/dsPID4W.X/src/dsPID4W.c#1220 <https://code.google.com/p/dspid4w/source/browse/trunk/dsPID4W.X/src/dsPID4W.c#1220>
> 
> You compute the (mean) speed at the PID rate, e.g.: every 1ms
> In this way you are measuring the total time for N pulses  occurred in 1ms (very close to 1ms but not exactly that because of discretization) = T
> Then you measure the total space traveled = number of pulses * space-for-each-pulse = S
> Then you divide the traveled space by the total period (about 1ms) = S/T = V
> 
> Simplifying and accepting a bit of approximation, you could even use T always = 1ms (or whatever PID sampling time), without measuring at all IC period, just counting the number of pulses occurred in between. At the contrary, if you want to be more precise, you can correct the measure calculating the difference between 1ms and the measured period.
> 
> Making a summation with the sign for the number of pulses:
> 
> https://code.google.com/p/dspid4w/source/browse/trunk/dsPID4W.X/src/dsPID4W.c#1370 <https://code.google.com/p/dspid4w/source/browse/trunk/dsPID4W.X/src/dsPID4W.c#1370>
> 
> takes care of the real traveled space, even if  the direction changes in between.
> 
> I hope tho have been clear enough:
> 1 - Get the period for one pulse 
> 2 - Sum the total time for N pulses occurred in one PID period
> 3 - Count, algebraically, the number of pulses N in one PID period
> 4 - Compute the space S traveled in one PID period multiplying N by space-for-each-pulse
> 5 - Compute the mean speed in one PID period = S/T
> 
> Of course this works if the period for one pulse is less then the PID period (at least one pulse in 1ms) and  the error is greater at low speed (less samples and therefore more quantization error).
> Changing the mode (rising, falling, rising and falling) allows a better dynamics at high speed. In order to work also at very-very low speed, the PID period should be increased in that cases, being careful to the K parameters that can change.
> 
> 
>> Question:
>> In this part of code we have to evaluate a mean value for sign (I remember this question in https://code.google.com/p/dspid4w/source/browse/trunk/dsPID4W.X/src/dsPID4W.c#1337 <https://code.google.com/p/dspid4w/source/browse/trunk/dsPID4W.X/src/dsPID4W.c#1337> @guiott <https://github.com/guiott> )
>> 
>> (QEI1CONbits.UPDN ? SIG_VELL++ : SIG_VELL--); //Save sign Vel L
>> It is same a:
>> SIG_VEL = K * QEIXCONbits.UPDN;
>> where K is number of starts for _ICXInterrupt function, but when we evaluate the velocity in https://github.com/officinerobotiche/uNAV.X/blob/develop/src/control/motors_PID.c#L350 <https://github.com/officinerobotiche/uNAV.X/blob/develop/src/control/motors_PID.c#L350>
>> motor.measure_vel = SIG_VEL * (parameter_motor.k_vel / timePeriod);
>> we obtain:
>> 
>> motor.measure_vel = K * QEIXCONbits.UPDN * (parameter_motor.k_vel / timePeriod);
>> but we have K times the correct measure of velocity!
>> 
>> I think to a correct evaluation of velocity we must use:
>> 
>> #define SGN(x)  ( ((x) < 0) ?  -1 : ( ((x) == 0 ) ? 0 : 1) )
>> motor.measure_vel = SGN(SIG_VEL) * (parameter_motor.k_vel / timePeriod);
>> cc @guiott <https://github.com/guiott>
>> —
>> Reply to this email directly or view it on GitHub <https://github.com/officinerobotiche/uNAV.X/pull/39#issuecomment-94266226>.
>> 
> 
> ___________________
> http://www.guiott.com/ <http://www.guiott.com/>
> 
> 
> 

___________________
http://www.guiott.com/

**Comment by rbonghi** [comment]
Splitted this branch in a simple part with new fuction to control motors.
When the pull request #44 is closed this branch will be updated.

**Pull request merged**
